/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window1_login;
  GtkWidget *window2_aff;
  GtkWidget *window3_ajout;
  GtkWidget *window4_modif;
  GtkWidget *window5_dashboard;
  GtkWidget *window6_rech;
GtkWidget *SMARTESPRIT;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ( "../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */

	
SMARTESPRIT=create_SMARTESPRIT();
gtk_widget_show (SMARTESPRIT);

/*
  window1_login = create_window1_login ();
  gtk_widget_show (window1_login);
 */ 

  gtk_main ();
  return 0;
}

